'use client'

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useQuiz } from "./store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Quize App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  quiz
}: Readonly<{
  children: React.ReactNode;
  quiz: React.ReactNode;
}>) {

  const config = useQuiz((state:any) => state.config);
  let render = config.status ==='start' ? quiz : children;

  return (
    <html lang="en">
      <body className={inter.className}>{render}</body>
    </html>
  );
}
